# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target "StarWarsQL" do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "GraphQLGerator", :path => "../"

  # Pods for StarWarsQL

  target "StarWarsQLTests" do
    inherit! :search_paths
  end

  target "StarWarsQLUITests" do
    inherit! :search_paths
    # Pods for testing
  end
end
